version: '3'

services:
  web:
    build: .
    command: sh -c "cd ./unluckystrike &&gunicorn main.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./unluckystrike/.env.dev
    depends_on:
      - db
  db:
    image: postgres:14.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=johyukjun
      - POSTGRES_PASSWORD=qkqh1214
      - POSTGRES_DB=unluckystrike_db
volumes:
  postgres_data: