version: '3'

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/unluckystrike/static
      - media_volume:/usr/src/app/unluckystrike/media
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
  certbot:
    image: certbot/certbot:arm32v6-nightly
    entrypoint: "/bin/sh -c 'cerbot certonly;'"
    # entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  web:
    build: .
    command: sh -c "cd ./unluckystrike && gunicorn main.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
      - static_volume:/usr/src/app/unluckystrike/static
      - media_volume:/usr/src/app/unluckystrike/media
    expose:
      - 8000
    env_file:
      - ./unluckystrike/.env.prod
    depends_on:
      - db
  db:
    image: postgres:14.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./unluckystrike/.env.prod.db
volumes:
  postgres_data:
  static_volume:
  media_volume: